config/routes.rb
RockCreek::Application.routes.draw do
  resources :change_types

  resources :statuses

  resources :change_requests

  get "signup_confirmations/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "signups#new", :as => "signup"
  get "dashboard" => "dashboard#show", :as => "dashboard"
  root :to => "home#index"
  resources :users
  resources :sessions
  resources :signups
  resources :signup_confirmations
  resources :change_requests
  resources :dashboard
  resources :invite_users
  resources :invitation_confirmations
  resources :request_response
  resources :admin

end

app/controllers/change_types_controller.rb
class ChangeTypesController < ApplicationController
  # GET /change_types
  # GET /change_types.json
  def index
    @change_types = ChangeType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @change_types }
    end
  end

  # GET /change_types/1
  # GET /change_types/1.json
  def show
    @change_type = ChangeType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @change_type }
    end
  end

  # GET /change_types/new
  # GET /change_types/new.json
  def new
    @change_type = ChangeType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @change_type }
    end
  end

  # GET /change_types/1/edit
  def edit
    @change_type = ChangeType.find(params[:id])
  end

  # POST /change_types
  # POST /change_types.json
  def create
    @change_type = ChangeType.new(params[:change_type])

    respond_to do |format|
      if @change_type.save
        format.html { redirect_to @change_type, notice: 'Change type was successfully created.' }
        format.json { render json: @change_type, status: :created, location: @change_type }
      else
        format.html { render action: "new" }
        format.json { render json: @change_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /change_types/1
  # PUT /change_types/1.json
  def update
    @change_type = ChangeType.find(params[:id])

    respond_to do |format|
      if @change_type.update_attributes(params[:change_type])
        format.html { redirect_to @change_type, notice: 'Change type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @change_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /change_types/1
  # DELETE /change_types/1.json
  def destroy
    @change_type = ChangeType.find(params[:id])
    @change_type.destroy

    respond_to do |format|
      format.html { redirect_to change_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/change_types_helper.rb
module ChangeTypesHelper
end

app/views/change_types/_form.html.erb
<%= form_for(@change_type) do |f| %>
  <% if @change_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@change_type.errors.count, "error") %> prohibited this change_type from being saved:</h2>

      <ul>
      <% @change_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/change_types/edit.html.erb
<h1>Editing change_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @change_type %> |
<%= link_to 'Back', change_types_path %>

app/views/change_types/index.html.erb
<h1>Listing change_types</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @change_types.each do |change_type| %>
  <tr>
    <td><%= link_to 'Show', change_type %></td>
    <td><%= link_to 'Edit', edit_change_type_path(change_type) %></td>
    <td><%= link_to 'Destroy', change_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Change type', new_change_type_path %>

app/views/change_types/new.html.erb
<h1>New change_type</h1>

<%= render 'form' %>

<%= link_to 'Back', change_types_path %>

app/views/change_types/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_change_type_path(@change_type) %> |
<%= link_to 'Back', change_types_path %>