config/routes.rb
RockCreek::Application.routes.draw do
  resources :change_types

  resources :statuses

  resources :change_requests

  get "signup_confirmations/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "signups#new", :as => "signup"
  get "dashboard" => "dashboard#show", :as => "dashboard"
  root :to => "home#index"
  resources :users
  resources :sessions
  resources :signups
  resources :signup_confirmations
  resources :change_requests
  resources :dashboard
  resources :invite_users
  resources :invitation_confirmations
  resources :request_response
  resources :admin

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    @change_requests = ChangeRequest.all

    respond_to do |format|
      format.html # showhtml.erb
      format.json { render json: @change_requests }
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/show.html.erb
<h1>ChangeControl Dashboard</h1>

<table class="table table-striped">
  <thead>
      <tr>
        <th>Requester</th>
        <th>Request Date</th>
        <th>Status</th>
        <th>Summary</th>
        <th>Change Type</th>
        <th>Assigned To</th>
        <th>Due Date</th>
        <th>Actions</th>
      </tr>
  </thead>

  <tbody>
  <% @change_requests.each do |change_request| %>
      <tr>
        <td><%= change_request.requester_name %></td>
        <td><%= change_request.request_date %></td>
        <td><%= change_request.status %></td>
        <td><%= change_request.summary %></td>
        <td><%= change_request.change_type %></td>
        <td><%= change_request.assigned_to_name %></td>
        <td><%= change_request.due_date %></td>
        <td>
            <% if allow? "change_requests", "show" %>
                <%= link_to 'Show', change_request, :class => 'btn btn-mini' %>
            <% end %>
            <% if allow? "change_requests", "edit", change_request%>
                <% if change_request.can_edit(@current_user) %>
                    <%= link_to 'Edit', edit_change_request_path(change_request), :class => 'btn btn-mini' %>
                <% end %>
            <% end %>
            <% if allow? "change_requests", "destroy" %>
                <%= link_to 'Destroy', change_request, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
            <% end %>
            <% if allow? "change_requests", "edit", change_request %>
                <% change_request.request_responses.each do |request_response| %>
                    <% if request_response.user_id == current_user.id && request_response.response == nil %>
                        <%=  link_to 'Approve', edit_request_response_path(:id => request_response.id, :response => "Approve"), :class => 'btn btn-mini' %>
                        <%=  link_to 'Deny', edit_request_response_path(:id => request_response.id, :response => "Deny"), :class => 'btn btn-mini' %>
                    <% end %>
                    <% if request_response.user_id == current_user.id && request_response.response == "Approve" %>
                        <%=  link_to 'Deny', edit_request_response_path(:id => request_response.id, :response => "Deny"), :class => 'btn btn-mini' %>
                    <% end %>
                    <% if request_response.user_id == current_user.id && request_response.response == "Deny" %>
                        <%=  link_to 'Approve', edit_request_response_path(:id => request_response.id, :response => "Approve"), :class => 'btn btn-mini' %>
                    <% end %>
                <% end %>
            <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>