config/routes.rb
RockCreek::Application.routes.draw do
  resources :change_types

  resources :statuses

  resources :change_requests

  get "signup_confirmations/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "signups#new", :as => "signup"
  get "dashboard" => "dashboard#show", :as => "dashboard"
  root :to => "home#index"
  resources :users
  resources :sessions
  resources :signups
  resources :signup_confirmations
  resources :change_requests
  resources :dashboard
  resources :invite_users
  resources :invitation_confirmations
  resources :request_response
  resources :admin

end

app/controllers/signup_confirmations_controller.rb
class SignupConfirmationsController < ApplicationController
  def new
  end

  def show
  end

  def edit
    # the ! raises a 404 if not found.
    @signup = Signup.find_by_email_confirmation_token!(params[:id])
  end

  def update
    @signup = Signup.find_by_email_confirmation_token!(params[:id])

    customer = Stripe::Customer.create(
        :card => @signup.stripe_token,
        :plan => @signup.plan_id,
        :email =>@signup.email
    )

    #customer = Stripe::Customer.create(
    #    :card => @signup.stripe_token,
    #    :description => @signup.email
    #)

    #Stripe::Charge.create(
    #    :amount => @signup.plan.price.to_int * 100,
    #    :currency => "usd",
    #    :customer => customer.id
    #)

    # create the tenant record
    @tenant = Tenant.new(:name => @signup.company, :subdomain => @signup.site_address, :stripe_customer_id => customer.id)
    @tenant.save

    # set the confirmed field on the user record.
    @user = User.find_by_email!(@signup.email)
    if @user.update_attributes(:tenant_id => @tenant.id, :first_name => @signup.first_name, :last_name => @signup.last_name, :confirmed => TRUE)
      session[:user_id] = @user.id
      #current_user

      #user_group_assignments
      #the first user to a subdomain should be an administrator.
      @assignment = UserGroupAssignment.new(:user_id => @user.id, :group_id => 1, :tenant_id => @tenant.id)
      @assignment.save

      redirect_to root_url(subdomain: @tenant.subdomain) +"/signup_confirmations/show.html"
    else
      render :edit
    end

    # link the user to the tenant

  end
end

app/helpers/signup_confirmations_helper.rb
module SignupConfirmationsHelper
end

app/views/signup_confirmations/edit.html.erb
<h1>Confirmation</h1>

<%= form_for @signup, :url => signup_confirmation_path(params[:id]) do |f| %>
    <% if @signup.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @signup.errors.full_messages %>
                <li><%=  message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="actions"><%= f.submit "Submit" %></div>
<% end %>

app/views/signup_confirmations/new.html.erb
<h1>Confirmation</h1>

<%= form_for @signup, :url => signup_confirmation_path(params[:id]) do |f| %>
    <% if @signup.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @signup.errors.full_messages %>
                <li><%=  message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="actions"><%= f.submit "Complete Confirmation" %></div>
<% end %>

app/views/signup_confirmations/show.html.erb
<title>Thank you for choosing to use ChangeControl</title>

<div class="container">
  <figure>

  </figure>
  <article>
    <h1>Thank you for choosing to use ChangeControl</h1>
    <p>We hope you will find it as useful as we do!</p>
    <nav>
      <%= button_to "Explore your new ChangeControl account!", dashboard_path, :method => "get" %>
    </nav>
  </article>
</div>